-- Monday coffee -- Data Analysis

-- Data Quality Checks

-- 1.NULL values

-- city
SELECT * FROM city
WHERE city_id IS NULL
   OR city_name IS NULL;

-- customers
SELECT * FROM customers
WHERE customer_id IS NULL
   OR city_id IS NULL;

-- products
SELECT * FROM products
WHERE product_id IS NULL
   OR price IS NULL;

-- sales
SELECT * FROM sales
WHERE sale_id IS NULL
   OR sale_date IS NULL
   OR product_id IS NULL
   OR customer_id IS NULL
   OR total IS NULL;

-- 2. Invalid Values

SELECT *
FROM sales
WHERE total < 0
   OR rating < 1
   OR rating > 5;


-- Q1. What is the total revenue generated by Monday Coffee?

SELECT SUM(total) As total_revenue
FROM sales;

-- Q2. How has monthly revenue changed over time?

SELECT DATE_TRUNC('month', sale_date) AS month, SUM(total) AS monthly_revenue
FROM sales
GROUP BY month
ORDER BY month ASC;

-- Q3. What is the average order value?

SELECT AVG(total) as average_order_value
FROM sales

-- Q4. Which are the top 10 products by total revenue?

SELECT p.product_name AS product_name, SUM(s.total) AS total_revenue
FROM products as p 
JOIN sales as s 
ON p.product_id = s.product_id
GROUP BY products
ORDER BY total_revenue DESC
LIMIT 10;

-- Q5. Which products are sold most frequently?

SELECT p.product_name, COUNT(s.sale_id) as sales_count
FROM products AS p
JOIN sales AS s
ON p.product_id = s.product_id
GROUP BY p.product_name
ORDER BY sales_count DESC
LIMIT 10;

-- Q6. Which products have the highest average customer ratings?

SELECT p.product_name, AVG(s.rating) AS average_rating, COUNT(s.sale_id) AS total_count_of_sales
FROM products AS p
JOIN sales AS s
ON p.product_id = s.product_id
GROUP BY p.product_name
HAVING COUNT(s.sale_id) >= 50
ORDER BY average_rating DESC
LIMIT 10;

-- Q7. Who are the top 10 customers by total spending?

SELECT c.customer_id, c.customer_name, SUM(s.total) as total_spending
FROM customers AS c
JOIN sales AS s
ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC
LIMIT 10;

-- Q8. What is the average number of purchases per customer?

SELECT AVG(purchase_count) AS avg_purchase_per_customer
FROM(
	SELECT customer_id, COUNT(sale_id) as purchase_count
	FROM sales
	GROUP BY customer_id
) AS customer_purchase

-- Q9. What percentage of customers are repeat customers?


WITH customer_purchases AS (
	SELECT customer_id, COUNT(sale_id) AS purchase_count
	FROM sales
	GROUP BY customer_id
)

SELECT 100 * COUNT(*) FILTER(WHERE purchase_count > 1) 
/ COUNT(*) AS repeat_customer_percentage
FROM customer_purchases;

-- Q10. Which cities generate the highest revenue?

SELECT c.city_id, c.city_name, SUM(s.total) as total_revenue
FROM city as c
JOIN customers as cu
ON c.city_id = cu.city_id
JOIN sales as s
ON cu.customer_id = s.customer_id
GROUP BY c.city_id, c.city_name
ORDER BY total_revenue DESC
LIMIT 10;

-- Q11. What is the revenue per customer in each city?

SELECT c.city_id, c.city_name, SUM(s.total) / COUNT(DISTINCT cu.customer_id) AS revenue_per_customer
FROM city AS c
JOIN customers AS cu
ON c.city_id = cu.city_id
JOIN sales AS s
ON cu.customer_id = s.customer_id
GROUP BY c.city_id, c.city_name
ORDER BY revenue_per_customer DESC;

-- Q12. Which city has the highest revenue per capita?

SELECT c.city_id, c.city_name, c.population, SUM(s.total) AS total_revenue, SUM(s.total) / c.population AS revenue_per_capita
FROM city AS c
JOIN customers AS cu
ON c.city_id = cu.city_id
JOIN sales AS s
ON cu.customer_id = s.customer_id
GROUP BY c.city_id, c.city_name, c.population
ORDER BY revenue_per_capita DESC
LIMIT 5;

-- Q13. Which city has the best revenue-to-rent ratio?

SELECT c.city_id, c.city_name, SUM(s.total) AS total_revenue, c.estimated_rent, SUM(s.total) / c.estimated_rent AS revenue_to_rent_ratio
FROM city AS c
JOIN customers AS cu
ON c.city_id = cu.city_id
JOIN sales AS s
ON cu.customer_id = s.customer_id
GROUP BY c.city_id, c.city_name, c.estimated_rent
ORDER BY revenue_to_rent_ratio DESC
LIMIT 5;

-- Q14. What is the best-selling product in each city?

WITH city_product_revenue AS (
SELECT c.city_id, c.city_name, p.product_name, SUM(s.total) as total_revenue
FROM city AS c
JOIN customers AS cu
ON c.city_id = cu.city_id
JOIN sales AS s
ON cu.customer_id = s.customer_id
JOIN products AS p
ON s.product_id = p.product_id
GROUP BY c.city_id, c.city_name, p.product_name
),
ranked_products AS(
SELECT city_id, city_name, product_name, total_revenue,
ROW_NUMBER() OVER(
PARTITION BY city_id
ORDER BY total_revenue DESC ) AS rank
FROM city_product_revenue) 


SELECT city_name, product_name, total_revenue FROM ranked_products
WHERE rank =1;

-- Q15. What is the month-over-month revenue growth rate?

WITH monthly_revenue AS(
SELECT DATE_TRUNC('month', sale_date) AS month, SUM(total) as monthly_revenue
FROM sales
GROUP BY month
)

SELECT month, monthly_revenue, LAG(monthly_revenue) OVER(ORDER BY month) AS previous_month_revenue,
(
(monthly_revenue - LAG(monthly_revenue) OVER(ORDER BY month)) * 100 / LAG(monthly_revenue) OVER(ORDER BY month)
) AS growth_percentage
FROM monthly_revenue
ORDER BY month;















